(define (translate letter)
  (cond ((equal? letter 'a) 'ALPHA)
        ((equal? letter 'b) 'BRAVO)
        ((equal? letter 'c) 'CHARLIE)
        ((equal? letter 'd) 'DENVER)
        ((equal? letter 'e) 'ELEPHANT)
        ((equal? letter 'f) 'FIELD)
        ((equal? letter 'g) 'GREEN)
        ((equal? letter 'h) 'HELLO)
        ((equal? letter 'i) 'INTER)
        ((equal? letter 'j) 'JAGUAR)
        ((equal? letter 'k) 'KIND)
        ((equal? letter 'l) 'LAMPSHADE)
        ((equal? letter 'm) 'MOON)
        ((equal? letter 'n) 'NEW)
        ((equal? letter 'o) 'OPERATE)
        ((equal? letter 'p) 'POTATO)
        ((equal? letter 'q) 'QUEBEC)
        ((equal? letter 'r) 'ROMEO)
        ((equal? letter 's) 'SIERRA)
        ((equal? letter 't) 'TANGO)
        ((equal? letter 'u) 'UNIFORM)
        ((equal? letter 'v) 'VICTOR)
        ((equal? letter 'w) 'WHISKEY)
        ((equal? letter 'x) 'XRAY)
        ((equal? letter 'y) 'YANKEE)
        ((equal? letter 'z) 'ZULU)))

(define (words str)
  (every translate (every sentence str)))